##############################################################
#            Projeto de Formatura I - SCC0670                #
#                                                            #
#      By: Artur Brenner Weber                               #
#      Last Update: 26/5/2026                                #
#                                                            #
###############################################################

# THE CODE BELOW IS EXPERIMENTAL (YOU HAVE BEEN WARNED PAL)
# Redirect the command log
set sh_command_log_file ./work/power_command.log

# Enable the PrimeTime power engine
set power_enable_analysis true

set TOP pe
set LIB_DB $env(SAED14_LIB_DB)

set search_path [list . ./work ./work/netlist]
set target_library [list $LIB_DB]
set link_library "* $target_library"

read_verilog work/netlist/pe_mapped.v
current_design $TOP
link_design $TOP

# Read constraints (clocks)
read_sdc work/netlist/pe_mapped.sdc

# Read switching activity generated by vcd2saif
read_saif work/dut.saif -strip_path tb_pe/dut

update_power

file mkdir $env(OUT_DIR)
report_power -hierarchy > $env(OUT_DIR)/power_hier_$env(BASE_ID).rpt

quit